version: 2.1

jobs:
  "elixir-1_8":
    docker:
      - image: circleci/elixir:1.8

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $CACHE_VERSION > cache.version

      - restore_cache:
          keys:
            - hex-packages-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - hex-packages-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
            - hex-packages-elixir-1.8-{{ .Environment.CACHE_VERSION }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - save_cache:
          key: hex-packages-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps

      - restore_cache:
          keys:
            - test-build-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - test-build-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
            - test-build-elixir-1.8-{{ .Environment.CACHE_VERSION }}
      - run: mix test
      - save_cache:
          key: test-build-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/test

      - restore_cache:
          keys:
            - dialyzer-plt-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - dialyzer-plt-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
            - dialyzer-plt-elixir-1.8-{{ .Environment.CACHE_VERSION }}
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: dialyzer-plt-elixir-1.8-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/dev

      - run: MIX_ENV=test mix coveralls.circle

      - store_artifacts:
          path: apps/tai/log
      - store_artifacts:
          path: apps/examples/log

  "elixir-1_9":
    docker:
      - image: circleci/elixir:1.9

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $CACHE_VERSION > cache.version

      - restore_cache:
          keys:
            - hex-packages-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - hex-packages-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
            - hex-packages-elixir-1.9-{{ .Environment.CACHE_VERSION }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - save_cache:
          key: hex-packages-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps

      - restore_cache:
          keys:
            - test-build-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - test-build-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
            - test-build-elixir-1.9-{{ .Environment.CACHE_VERSION }}
      - run: mix test
      - save_cache:
          key: test-build-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/test

      - restore_cache:
          keys:
            - dialyzer-plt-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - dialyzer-plt-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
            - dialyzer-plt-elixir-1.9-{{ .Environment.CACHE_VERSION }}
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: dialyzer-plt-elixir-1.9-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/dev

      - run: MIX_ENV=test mix coveralls.circle

      - store_artifacts:
          path: apps/tai/log
      - store_artifacts:
          path: apps/examples/log

workflows:
  version: 2
  build:
    jobs:
      - "elixir-1_8"
      - "elixir-1_9"
