version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - hex-packages-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - save_cache:
          key: hex-packages-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps

      - restore_cache:
          keys:
            - test-build-{{ arch }}-{{ .Branch }}
      - run: mix test
      - save_cache:
          key: test-build-{{ arch }}-{{ .Branch }}
          paths:
            - _build/test

      - run: MIX_ENV=test mix coveralls.circle
