version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - hex-packages-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - hex-packages-{{ arch }}-{{ .Branch }}
            - hex-packages
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - save_cache:
          key: hex-packages-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps

      - restore_cache:
          keys:
            - test-build-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - test-build-{{ arch }}-{{ .Branch }}
            - test-build
      - run: mix test
      - save_cache:
          key: test-build-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/test

      - restore_cache:
          keys:
            - dialyzer-plt-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
            - dialyzer-plt-{{ arch }}-{{ .Branch }}
            - dialyzer-plt
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: dialyzer-plt-{{ arch }}-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/dev

      - run: MIX_ENV=test mix coveralls.circle
